Fixed building UWP app using Unity 2019
Microsoft/AppCenter-SDK-Unity pull request #269
Opened 2019-05-31 12:58 UTC by AndreiShilkin

Fixed `Debugger.cpp` generation logic.

2019-05-31 13:00 UTC, annakocheshkova submitted a review, later dismissed

2019-05-31 13:00 UTC, dtrabo submitted a review, later dismissed

2019-05-31 15:39 UTC, MatkovIvan requested changes

2019-05-31 15:39 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +        codeLines.Insert(lastIncludeLineIndex + 2, "#undef GetCurrentDirectory");
Please add comment WHY it works

2019-06-03 06:49 UTC, AndreiShilkin commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +        codeLines.Insert(lastIncludeLineIndex + 2, "#undef GetCurrentDirectory");
Done

2019-06-03 07:23 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +        codeLines.Insert(lastIncludeLineIndex + 1, "#include <Windows.h>");
```suggestion
        // Add '#include <Windows.h>' which provides 'OutputDebugStringW'.
        codeLines.Insert(lastIncludeLineIndex + 1, "#include <Windows.h>");
```

2019-06-03 07:23 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +        // Add logging method.
```suggestion

        // Add logging method.
```

2019-06-03 07:23 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +        codeLines.Insert(lastIncludeLineIndex + 2, "#undef GetCurrentDirectory");
```suggestion
        /*
         * 'GetCurrentDirectory' define conflicts with generated code and new versions of Unity
         * combine some files on the compilation so the changes in one file can affect another.
         */
        codeLines.Insert(lastIncludeLineIndex + 2, "#undef GetCurrentDirectory");
```

2019-06-03 07:23 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +        // Enable logging.
```suggestion

        // Enable logging.
```

2019-06-03 07:23 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +
```suggestion
```

2019-06-03 07:23 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +
```suggestion
```

2019-06-03 07:34 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterPostBuild.cs
> +    /**
Use C# xml-doc

2019-06-03 07:43 UTC, MatkovIvan submitted a review, later dismissed

2019-06-03 08:22 UTC, AndreiShilkin commented
_Notes:_
We have to use `WriteAllLines(String, String[])` method overloading to have backward compatibility with Unity 2017. [Link to docs.](https://docs.microsoft.com/ru-ru/dotnet/api/system.io.file.writealllines?view=netframework-3.5)

2019-06-03 14:15 UTC, MatkovIvan approved these changes

2019-06-04 17:39 UTC, merged