Fixed enabled Crashes
Microsoft/AppCenter-SDK-Unity pull request #276
Opened 2019-07-09 12:13 UTC by AnastasiaKubova

## Description
Crashes should be enabled again after disabled Crashes / App Center.

##Related PRs or issues
AB#63938

2019-07-09 18:36 UTC, guperrot submitted a review, later dismissed

2019-07-10 08:27 UTC, annakocheshkova submitted a review, later dismissed

2019-07-10 11:54 UTC, MatkovIvan requested changes

2019-07-10 11:54 UTC, MatkovIvan commented on Assets/Puppet/PuppetCrashes.cs
> +        StartCoroutine(SetCrashesEnabledCoroutine(CrashesEnabled.isOn));
Incorrect fix. Please just change the parameter to dynamic in UI

2019-07-10 13:11 UTC, MatkovIvan submitted a review, later dismissed

2019-07-11 09:58 UTC, MatkovIvan approved these changes

2019-07-11 09:58 UTC, annakocheshkova approved these changes

2019-07-12 08:06 UTC, merged