Update changelog
Microsoft/AppCenter-SDK-Unity pull request #293
Opened 2019-08-01 14:34 UTC by annakocheshkova

2019-08-01 18:26 UTC, guperrot requested changes

2019-08-01 18:26 UTC, guperrot commented on CHANGELOG.md
>  ## Release 2.2.1 (Under development)
```suggestion
## Release 2.3.0 (Under development)
```

It's a feature.

2019-08-01 18:26 UTC, guperrot commented on CHANGELOG.md
> +* **[Feature]** Catch "low memory warning" and provide the API to check if it has happened in last session:  `Crashes.HasReceivedMemoryWarningInLastSessionAsync`.
```suggestion
* **[Feature]** Catch "low memory warning" and provide the API to check if it has happened in last session:  `Crashes.HasReceivedMemoryWarningInLastSessionAsync()`.
```

2019-08-01 20:01 UTC, guperrot approved these changes

2019-08-02 07:22 UTC, MatkovIvan approved these changes

2019-08-02 07:22 UTC, merged