[Fix] 2019.3 build
Microsoft/AppCenter-SDK-Unity pull request #350
Opened 2019-10-31 10:29 UTC by annakocheshkova

Fixes #349 
To be released in 2.5.0

2019-10-31 12:11 UTC, annakocheshkova commented
It fails with license once again...

2019-10-31 13:08 UTC, russelarms submitted a review, later dismissed

2019-10-31 16:54 UTC, jaeklim submitted a review, later dismissed

2019-10-31 17:42 UTC, thyeggman submitted a review, later dismissed

2019-10-31 18:42 UTC, guperrot requested changes
Looks good but changelog is missing.

2019-11-01 18:42 UTC, guperrot approved these changes

2019-11-01 18:42 UTC, merged