Fix/unity android build obsolete warning
Microsoft/AppCenter-SDK-Unity pull request #393
Opened 2020-01-15 08:59 UTC by olmisa

Things to consider before you submit the PR:

* [x] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] Did you add unit tests if this modifies the Windows code?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

Providing Android resources from the Unity 'Plugins' folder was deprecated. The code was reworked. Now the application settings file creates as 'AppCenterLoader' library resource.

## Related PRs or issues

AB#72139

2020-01-15 10:01 UTC, annakocheshkova commented on Assets/AppCenter/Editor/AppCenterPreBuild.cs
> +        // Delete the AndroidManifest.xml.meta file if generated
Fix the comment

2020-01-15 10:23 UTC, olmisa commented on Assets/AppCenter/Editor/AppCenterPreBuild.cs
> +        // Delete the AndroidManifest.xml.meta file if generated
Fixed

2020-01-15 19:06 UTC, guperrot requested changes
What kind of tests were done for this as this changes integration build a bit. Did we verify a blank app and demo upgrade?

2020-01-15 19:06 UTC, guperrot commented on Assets/AppCenter/Editor/AndroidLibraryHelper.cs
> +﻿using System.Diagnostics;
copyright missing

2020-01-15 19:06 UTC, guperrot commented on Assets/AppCenter/Editor/AppCenterPreBuild.cs
> +        var settingsFilePath = "appcenter-loader-release/res/values/appcenter-settings.xml";
folder name could be appended from loaderFolder, and maybe use constants for all of these paths

2020-01-15 19:06 UTC, guperrot commented on Assets/AppCenter/Editor/AppCenterPreBuild.cs
> +        // Delete unzipeed directory if it already exists.
typo
```suggestion
        // Delete unzipped directory if it already exists.
```

2020-01-15 19:06 UTC, guperrot commented on Assets/AppCenter/Editor/AppCenterPreBuild.cs
> +        // Delete the appcenter-settings.xml.meta file if generated
End comments with dots.
```suggestion
        // Delete the appcenter-settings.xml.meta file if generated.
```

2020-01-15 19:06 UTC, guperrot commented on Assets/AppCenter/Editor/AppCenterSettingsMakerAndroid.cs
> +    private const string AppCenterResourcesFolderPath = "AppCenterLoaderApp/appcenter-loader/src/main/res/values/";
the path constants should be shared with the other file

2020-01-15 20:49 UTC, olmisa commented
The changes were verified on a demo and on the blank app.

2020-01-15 20:51 UTC, guperrot commented on Assets/AppCenter/Editor/AppCenterPreBuild.cs
> +        string loaderZipFile = AppCenterSettingsContext.AppCenterPath + "/Plugins/Android/appcenter-loader-release.aar";
```suggestion
        var loaderZipFile = AppCenterSettingsContext.AppCenterPath + "/Plugins/Android/appcenter-loader-release.aar";
```

2020-01-15 20:52 UTC, guperrot commented on CHANGELOG.md
> +* **[Fix]** Fix the Unity warning that appears during the building app for Android.
```suggestion
* **[Fix]** Fix a Unity warning that appears when building for Android.
```

2020-01-15 22:01 UTC, guperrot approved these changes

2020-01-16 18:57 UTC, merged

2020-03-26 14:45 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterSettingsMakerAndroid.cs
> +    public const string AppCenterLoaderResourcesPath = AppCenterLoaderResourcesFolderPath + "appcenter-settings.xml";
This is totally incorrect. @olmisa please revert it

2020-03-26 14:52 UTC, MatkovIvan commented on Assets/AppCenter/Editor/AppCenterSettingsMakerAndroid.cs
> +    public const string AppCenterLoaderResourcesFolderPath = "AppCenterLoaderApp/appcenter-loader/src/main/res/values/";
It doesn't work. It must not write to this location, it doesn't make any sense if there are no SDK sources in project's location