Update changelog and readme
Microsoft/AppCenter-SDK-Unity pull request #421
Opened 2020-03-04 11:08 UTC by russelarms

Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?

## Description

Update changelog and readme.

## Related PRs or issues

[AB#77375](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/77375)

2020-03-04 11:17 UTC, annakocheshkova commented on CHANGELOG.md
> +* **[Feature]** App Center SDK supports **arm64** on UWP.
Maybe it's better to use the sentence from DorNet:
> [Feature] Support ARM64 architecture.

2020-03-04 19:43 UTC, guperrot commented on README.md
> +The App Center Unity SDK enables you to use App Center Analytics, Crash and Distribution within your Unity games.
```suggestion

The App Center Unity SDK enables you to use App Center Analytics, Crash and Distribution within your Unity games.
```

2020-03-04 19:51 UTC, MatkovIvan requested changes

2020-03-04 19:51 UTC, MatkovIvan commented on README.md
>  * UWP (Build 10240 or later)
16299

2020-03-04 19:51 UTC, MatkovIvan commented on CHANGELOG.md
> +#### UWP
We dropping support for .NET scripting backend

2020-03-04 19:51 UTC, MatkovIvan commented on CHANGELOG.md
> +* **[Feature]** App Center SDK supports **arm64** on UWP.
ARM64 only supported by Unity 2019.x or above

2020-03-05 19:27 UTC, guperrot commented on CHANGELOG.md
> +* **[Fix]** Fixed `async`/`await` operators support by SDK's methods for .NETStandard 2.0 profile
```suggestion
* **[Fix]** Fixed `async`/`await` operators support by SDK's methods for .NETStandard 2.0 profile.
```

2020-03-05 19:27 UTC, guperrot commented on CHANGELOG.md
>  * **[Fix]** Fixed iOS application crash when trying to pass exception without stack trace to `Crashes.TrackError`
```suggestion
* **[Fix]** Fixed iOS application crash when trying to pass exception without stack trace to `Crashes.TrackError`.
```

2020-03-09 20:48 UTC, guperrot approved these changes

2020-03-10 15:23 UTC, MatkovIvan approved these changes

2020-03-10 15:23 UTC, merged